### ISSUE TITLE
"#content" is below "#mainmenu" 

### ISSUE THREAD

**Issue by fydo23** [fydo23/mySurvey#12]
![screen shot 2013-10-20 at 11 22 40 pm](https://f.cloud.github.com/assets/1847706/1369728/16c84576-3a00-11e3-8f13-e42d2ba7eff7.png)

**Comment by imaadkhan87** [comment]
For me this issue only comes up when I use chrome. It looks fine on Safari.

**Comment by fydo23** [comment]
Chrome. +1

**Comment by fdemiri** [comment]
Chrome +1. Same thing on Internet Explorer too.

**Comment by gjensen01** [comment]
Fixed! Updated the width of #mainmenu.
