### ISSUE TITLE
Error div shifts title field when creating a survey with title < 6 characters

### ISSUE THREAD

**Issue by imaadkhan87** [fydo23/mySurvey#13]
![screen shot 2013-10-24 at 3 32 24 am](https://f.cloud.github.com/assets/5456570/1397082/877b418a-3c7e-11e3-90f9-f06d4456ee29.png)

**Comment by dualv** [comment]
This also happens on survey question text.

**Comment by fydo23** [comment]
hook jquery form submission event to add the error class after failed ajax validation.

**Comment by gjensen01** [comment]
Mostly fixed. Please update javascript to add "error" class to the parent ".row"

**Comment by fdemiri** [comment]
This has been fixed in the latest master as well.
