### ISSUE TITLE
re-ordering questions shouldn't save on drop. 

### ISSUE THREAD

**Issue by fydo23** [fydo23/mySurvey#14]

**Comment by fydo23** [comment]
combine the #survey-form in survey/_form to include the #question_order div so that the ordering is passed in the same form. I suggest removing the inclusion of _form in survey/update and re-creating the combined form right in survey/update. Then, in surveyQuestion, add the actionReorderQuestions logic into the actionUpdate. Make sure to handle the post information before defining the questions_dataProvider. finally remove the $.post call in the static/js/fucntions call in the //DRAGGABLE CONTENT section.

**Comment by fydo23** [comment]
The update survey page has links to update specific questions.. After editing the title of the survey, if a user clicks on edit or create question, the survey title changes are lost because the user navigates away before submitting the survey title changes. Instead of having the save buttons, I'm going to have the title save on input blur event.

**Comment by fydo23** [comment]
gloria, can you take a look and see if this works to solve the above issue from the UX perspective??

**Comment by fdemiri** [comment]
I think this is fixed.
