### ISSUE TITLE
Client side validation for registration and login form not working.

### ISSUE THREAD

**Issue by dualv** [fydo23/mySurvey#15]
Validation only happens when you the form is submitted. Client side validation not working when field is changed. Moving script linking from near the end of body into header in home.php and main.php seems to fix it.

**Comment by dualv** [comment]
If others can verify the fix is correct, I'll make a commit and push it to the main branch.

**Comment by fdemiri** [comment]
I think the validation is working now but the fields move to the left when the error is shown. It might need a styling fix as well.
Does this happen for anybody else?

**Comment by dualv** [comment]
Yes, I'm having the same problem, it shifts left when the error is shown.

**Comment by fdemiri** [comment]
I think this is fixed in the latest version of master.
