### ISSUE TITLE
Saving a question with empty answers makes the "Add new asnwer" button dissapear

### ISSUE THREAD

**Issue by fdemiri** [fydo23/mySurvey#17]
![image](https://f.cloud.github.com/assets/5480538/1534277/d934b56e-4c92-11e3-9cca-5433de9b5bc7.png)

**Comment by fydo23** [comment]
I can't re-create this. Can you either make sure this is still an issue, or how I can re-create it exactly? Use Devl.

**Comment by fdemiri** [comment]
This seems to be fixed.
