### ISSUE TITLE
Allow saving question without an answer?

### ISSUE THREAD

**Issue by fdemiri** [fydo23/mySurvey#22]
I wonder if we should allow this and display just the question with no answers.

I would say allow it. What do you think?

**Comment by fydo23** [comment]
It just doesn't make sense to me why we should allow an answer-less and un-reportable question, but it would take more work to add validation for question without any answer. You are the customer though so what do you think? Is saving a multiple choice without answers a feature or a bug???

**Comment by fdemiri** [comment]
As a customer I agree, but I want to give it low priority.
I created a Pivotal Tracker story for it.

**Comment by fdemiri** [comment]
Btw Fyodor, I went through your JavaScript code for question type logic, and looked really good. 
Great job! I liked the strategy pattern there.
