### ISSUE TITLE
Download as csv problem on exported version

### ISSUE THREAD

**Issue by bethh** [fydo23/mySurvey#28]
I found a bug with the Download button.

I created a survey on the BU machine under Chih-Chi's login called "My New Survey 1".  And I tried to download it.
1. It downloads with the name "My" instead of the full name.
2. It doesn't download it in csv format.  The format is "file".

**Comment by dualv** [comment]
This seems to be caused by white space in the survey title, including white space from the time format, added fix to the main branch. Please test it and let me know if it works.

**Comment by fdemiri** [comment]
dualv this is working now.
