### ISSUE TITLE
Remove url from survey model.

### ISSUE THREAD

**Issue by fdemiri** [fydo23/mySurvey#5]
We should remove the url from the model. It should be automatically generated from the survey ID and user email etc.

**Comment by fydo23** [comment]
Didn't we agree to only have a single url? This ensures that when someone sends a url via an external service, they don't need to send hundreds of different links... 

Let's brainstorm this a bit.

**Comment by fydo23** [comment]
After some research, I realized the only really SECURE and EFFICIENT way of doing this is generating another unique hash that is also stored in the db column. (inline with our original thinking...)

Suggestion: How about renaming the 'url' field to 'hash' as a unique field that is generated during survey creation? It will be indexed for faster lookup and it won't need to be encoded/decoded every-time someone requests a survey url.

**Comment by fdemiri** [comment]
That sounds like a good idea. Then we need to find a way to show the survey url to the survey creator after is created.

**Comment by fydo23** [comment]
Perhaps something along the lines of: /survey/take/<unique_hash>??? This isn't much different from just using the id, but it's at least a little more abstract and slightly harder to guess...

**Comment by fdemiri** [comment]
I was thinking something like that too.

**Comment by bethh** [comment]
Since this has evolved from being a bug to being an enhancement, maybe we should move the discussion to Survey URL in PivotalTracker?  To be consistent with the bugs-on-Github, requirements-on-PivotalTracker.  Thoughts?

**Comment by fydo23** [comment]
Agreed...

bethh notifications@github.com wrote:

Since this has evolved from being a bug to being an enhancement, maybe we should move the discussion to Survey URL in PivotalTracker? To be consistent with the bugs-on-Github, requirements-on-PivotalTracker. Thoughts?

**Comment by fydo23** [comment]
Url field in survey model should be renamed to 'hash' which will store a unique hash of length 8 hex-dec characters yielding half a billion possibilities.

Tasks:
    1) create migration.
    2) generate models/views
    3) replace /protected/views/survey views.
    4) modify theme views to correlate accordingly.

**Comment by fdemiri** [comment]
I agree. There is Pivotal story for this. I added the tasks as well.

**Comment by fdemiri** [comment]
I am closing this since it is in Pivotal Tracker
