### ISSUE TITLE
Inserts into the 'created' column of Survey table does not seem to insert the correct current time.

### ISSUE THREAD

**Issue by fdemiri** [fydo23/mySurvey#8]
Inserts into the 'created' column of Survey table does not seem to insert the correct current time using (new DateTime('NOW'))->format('c')) as it is in the SurveyController.php
I tested using new CDbExpression('NOW()') which gives the correct time in the test cases. I don't know if this is just the case on my machine though.

**Comment by fydo23** [comment]
Your solution of CDbExpression is the proper way to do it. I applied the fix and this is fixed and on Master..
